apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ssocxsg42-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ssocxsg42-go 
  name: ssocxsg42-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ssocxsg42-go 
